#!/bin/bash

composer install
composer require laravel/socialite

sudo mysql <<EOF
CREATE DATABASE dss2026 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'dss2026'@'localhost' IDENTIFIED BY 'dss2026';
GRANT ALL PRIVILEGES ON dss2026.* TO 'dss2026'@'localhost';
FLUSH PRIVILEGES;
EOF

cat > .env <<'EOF'
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:Q0TxZvDQv/fWKsCmnYG65zEGuIdoICxuG3TJm93SWCw=
APP_DEBUG=true
APP_TIMEZONE=UTC
APP_URL=http://localhost

APP_LOCALE=es
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US

APP_MAINTENANCE_DRIVER=file

PHP_CLI_SERVER_WORKERS=4

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=dss2026
DB_USERNAME=dss2026
DB_PASSWORD=dss2026

SESSION_DRIVER=file
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database

CACHE_STORE=database
CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1

REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=465
MAIL_USERNAME=espaciua@gmail.com
MAIL_PASSWORD=ebcsubuisfzlsbzw
MAIL_ENCRYPTION=ssl
MAIL_FROM_ADDRESS="espaciua@gmail.com"
MAIL_FROM_NAME="EspaciUA"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

VITE_APP_NAME="${APP_NAME}"

GOOGLE_CLIENT_ID=854168282865-b3skbr4lg9d716omam2l94uapuevjpvu.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=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
GOOGLE_REDIRECT=http://127.0.0.1:8000/auth/google/callback
EOF

php artisan migrate:fresh --seed
